#!/usr/bin/env tsx

/**
 * Set up local development environment with dependencies and configuration.
 * - Installs project dependencies with pnpm
 * - BETTER_AUTH_SECRET: 32 bytes for session signing (also needed in Convex Dashboard)
 * Run: pnpm run setup:env
 */

import { execSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { generateSecret } from '../src/lib/server/crypto.server';
import { requireCommands } from './lib/cli-preflight';
import { DEFAULT_APP_NAME } from './lib/setup-defaults';

function printUsage() {
  console.log('Usage: pnpm run setup:env');
  console.log('');
  console.log('What this does:');
  console.log('- Installs pnpm dependencies');
  console.log('- Creates .env.local when missing');
  console.log('- Generates a BETTER_AUTH_SECRET for local development');
  console.log('');
  console.log('Safe to rerun: yes');
  console.log(
    '- Existing .env.local is preserved; the script prints the generated secret instead.',
  );
}

async function main() {
  if (process.argv.includes('--help') || process.argv.includes('-h')) {
    printUsage();
    return;
  }

  console.log('🔧 Setting up local development environment...\n');
  console.log('What this does: install dependencies and create local defaults in .env.local.');
  console.log('Prereqs: pnpm on PATH.');
  console.log('Modifies: pnpm lockfile/node_modules via install, plus .env.local if missing.');
  console.log('Safe to rerun: yes; existing .env.local is not overwritten.\n');
  requireCommands([{ cmd: 'pnpm' }]);

  // Install project dependencies
  console.log('📦 Installing project dependencies...');
  try {
    execSync('pnpm install', { stdio: 'inherit', cwd: process.cwd() });
    console.log('✅ Dependencies installed successfully!\n');
  } catch {
    console.error('❌ Failed to install dependencies. Please run: pnpm install');
    process.exit(1);
  }

  const authSecret = await generateSecret(32); // BETTER_AUTH_SECRET: 32 bytes for session signing and rate limiting

  const envPath = join(process.cwd(), '.env.local');

  // Check if .env.local already exists
  if (existsSync(envPath)) {
    console.log('⚠️  .env.local already exists!');
    console.log('   To avoid overwriting existing configuration, here are your generated secrets:');
    console.log('────────────────────────────────────────────────');
    console.log(`BETTER_AUTH_SECRET=${authSecret}`);
    console.log('────────────────────────────────────────────────\n');
    console.log('📝 Add these to your existing .env.local file.');
    return;
  }

  // Create .env.local with all defaults
  const envContent = `# Local Development Environment
# Generated by: pnpm run setup:env
# Generated on: ${new Date().toISOString()}

# ==========================================
# REQUIRED SECRETS (Generated Securely)
# ==========================================

# Signs JWTs for authentication and protects internal rate limiting operations
BETTER_AUTH_SECRET=${authSecret}

# ==========================================
# REQUIRED DEFAULTS
# ==========================================

# Set development environment
NODE_ENV=development

# Better Auth base URL. Use 127.0.0.1 so local browser automation shares one origin.
BETTER_AUTH_URL=http://127.0.0.1:3000

# Application name (passkeys, Convex sync via setup:convex)
APP_NAME="${DEFAULT_APP_NAME}"

# ==========================================
# OPENROUTER AI SETUP (Optional but recommended for chat)
# ==========================================

# Required for chat functionality
# OPENROUTER_API_KEY=<your-openrouter-api-key>

# OpenRouter attribution uses BETTER_AUTH_URL and APP_NAME automatically

# ==========================================
# RESEND EMAIL SETUP
# ==========================================
#
# RESEND_API_KEY=<your-resend-api-key>          # Optional: for email functionality
# RESEND_EMAIL_SENDER=onboarding@resend.dev     # Optional: sender shown in email flows

# ==========================================
# STORAGE
# ==========================================

# Storage defaults to FILE_STORAGE_BACKEND=convex.
# Run pnpm run storage:setup if you want guided setup for:
#   - convex
#   - s3
#   - mirror
# FILE_STORAGE_BACKEND=convex
# AWS_REGION=us-west-1
# AWS_PROFILE=default
# AWS_S3_QUARANTINE_BUCKET=your-dev-storage-quarantine
# AWS_S3_CLEAN_BUCKET=your-dev-storage-clean
# AWS_S3_REJECTED_BUCKET=your-dev-storage-rejected
# AWS_S3_MIRROR_BUCKET=your-dev-storage-mirror
# AWS_S3_QUARANTINE_KMS_KEY_ARN=arn:aws:kms:us-west-1:123456789012:alias/tanstack-start-template-dev-quarantine
# AWS_S3_CLEAN_KMS_KEY_ARN=arn:aws:kms:us-west-1:123456789012:alias/tanstack-start-template-dev-clean
# AWS_S3_REJECTED_KMS_KEY_ARN=arn:aws:kms:us-west-1:123456789012:alias/tanstack-start-template-dev-rejected
# AWS_S3_MIRROR_KMS_KEY_ARN=arn:aws:kms:us-west-1:123456789012:alias/tanstack-start-template-dev-mirror
# AWS_GUARDDUTY_WEBHOOK_SHARED_SECRET=<generated-secret>
# AWS_STORAGE_INSPECTION_WEBHOOK_SHARED_SECRET=<generated-secret>
# AWS_FILE_SERVE_SIGNING_SECRET=<generated-secret>
# AWS_STORAGE_ROLE_ARN_UPLOAD_PRESIGN=arn:aws:iam::123456789012:role/tanstack-start-template-dev-storage-upload-presign
# AWS_STORAGE_ROLE_ARN_DOWNLOAD_PRESIGN=arn:aws:iam::123456789012:role/tanstack-start-template-dev-storage-download-presign
# AWS_STORAGE_ROLE_ARN_PROMOTION=arn:aws:iam::123456789012:role/tanstack-start-template-dev-storage-promotion
# AWS_STORAGE_ROLE_ARN_REJECTION=arn:aws:iam::123456789012:role/tanstack-start-template-dev-storage-rejection
# AWS_STORAGE_ROLE_ARN_CLEANUP=arn:aws:iam::123456789012:role/tanstack-start-template-dev-storage-cleanup
# AWS_STORAGE_ROLE_ARN_MIRROR=arn:aws:iam::123456789012:role/tanstack-start-template-dev-storage-mirror
# CONVEX_SITE_URL=https://your-project.convex.site

# ==========================================
# SENTRY ERROR MONITORING (Optional)
# ==========================================

# Optional: Sentry DSN for error monitoring and performance tracking
# Get from: https://sentry.io/settings/projects/YOUR_PROJECT/keys/
# VITE_SENTRY_DSN=https://your-project-dsn.ingest.sentry.io/project-id
# Leave commented out to disable Sentry monitoring

# ==========================================
# CONVEX DATABASE (Auto-configured)
# ==========================================

# Convex URLs will be automatically set after running: pnpm exec convex dev
# VITE_CONVEX_URL=https://your-project.convex.cloud
#
# After editing synced keys: pnpm run setup:convex
# Drift check (local vs Convex dev): pnpm run convex:env:verify
# Drop unused Convex env vars: pnpm run convex:env:hygiene

# ==========================================
# PLAYWRIGHT E2E AUTH (Optional)
# ==========================================

# Enable only when you want authenticated E2E seeding/login helpers
# ENABLE_E2E_TEST_AUTH=true
# E2E_TEST_SECRET=<shared-secret-for-test-route>
# E2E_USER_EMAIL=e2e-user@local.test
# E2E_USER_PASSWORD=<deterministic-test-password>
# E2E_USER_NAME="E2E User"
# E2E_ADMIN_EMAIL=e2e-admin@local.test
# E2E_ADMIN_PASSWORD=<deterministic-test-password>
# E2E_ADMIN_NAME="E2E Admin"

`;

  writeFileSync(envPath, envContent, 'utf8');

  console.log('✅ Local development environment configured!');
  console.log(`   📁 Created: ${envPath}`);
  console.log('────────────────────────────────────────────────');
  console.log('🔑 Generated Secrets:');
  console.log(`   BETTER_AUTH_SECRET: ${authSecret.substring(0, 10)}...`);
  console.log('────────────────────────────────────────────────\n');
  console.log('🚀 Next steps:');
  console.log('   1. 📋 Review the generated .env.local file');
  console.log('   2. ☁️  Run: pnpm exec convex dev --once (initialize Convex project)');
  console.log('   3. ⚙️  Run: pnpm run setup:convex (configure URLs & env vars)');
  console.log('   4. 🔄 Terminal 1: pnpm exec convex dev (start Convex backend)');
  console.log('   5. 🎯 Terminal 2: pnpm dev (start frontend development)');
  console.log('');
  console.log("💡 Tip: After step 5, you'll never need to run setup again!");
  console.log(
    '   Future development: run "pnpm exec convex dev" in one terminal and "pnpm dev" in another',
  );
  console.log('\n📌 Security Notes:');
  console.log('   • Never commit .env.local to version control');
  console.log('   • Back up these secrets if they guard real data');
  console.log('   • Convex handles encryption at the platform level');
}

main().catch((error) => {
  console.error('\n❌ Failed to set up development environment');
  console.error(error);
  process.exit(1);
});
