#!/usr/bin/env tsx

/**
 * Set up local development environment with dependencies and configuration.
 * - Installs project dependencies with pnpm
 * - BETTER_AUTH_SECRET: 32 bytes for session signing (also needed in Convex Dashboard)
 * Run: pnpm run setup:env
 */

import { execSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { generateSecret } from '../src/lib/server/crypto.server';
import { DEFAULT_APP_NAME } from './lib/setup-defaults';

async function main() {
  console.log('🔧 Setting up local development environment...\n');

  // Install project dependencies
  console.log('📦 Installing project dependencies...');
  try {
    execSync('pnpm install', { stdio: 'inherit', cwd: process.cwd() });
    console.log('✅ Dependencies installed successfully!\n');
  } catch {
    console.error('❌ Failed to install dependencies. Please run: pnpm install');
    process.exit(1);
  }

  const authSecret = await generateSecret(32); // BETTER_AUTH_SECRET: 32 bytes for session signing and rate limiting

  const envPath = join(process.cwd(), '.env.local');

  // Check if .env.local already exists
  if (existsSync(envPath)) {
    console.log('⚠️  .env.local already exists!');
    console.log('   To avoid overwriting existing configuration, here are your generated secrets:');
    console.log('────────────────────────────────────────────────');
    console.log(`BETTER_AUTH_SECRET=${authSecret}`);
    console.log('────────────────────────────────────────────────\n');
    console.log('📝 Add these to your existing .env.local file.');
    return;
  }

  // Create .env.local with all defaults
  const envContent = `# Local Development Environment
# Generated by: pnpm run setup:env
# Generated on: ${new Date().toISOString()}

# ==========================================
# REQUIRED SECRETS (Generated Securely)
# ==========================================

# Signs JWTs for authentication and protects internal rate limiting operations
BETTER_AUTH_SECRET=${authSecret}

# ==========================================
# REQUIRED DEFAULTS
# ==========================================

# Set development environment
NODE_ENV=development

# Better Auth base URL. Use 127.0.0.1 so local browser automation shares one origin.
BETTER_AUTH_URL=http://127.0.0.1:3000

# Application name (passkeys, Convex sync via setup:convex)
APP_NAME="${DEFAULT_APP_NAME}"

# ==========================================
# OPENROUTER AI SETUP (Optional but recommended for chat)
# ==========================================

# Required for chat functionality
# OPENROUTER_API_KEY=<your-openrouter-api-key>

# Optional attribution headers
# OPENROUTER_SITE_URL=http://127.0.0.1:3000
# OPENROUTER_SITE_NAME="TanStack Start Template"

# ==========================================
# RESEND EMAIL SETUP
# ==========================================
#
# RESEND_API_KEY=<your-resend-api-key>          # Optional: for email functionality
# RESEND_EMAIL_SENDER=onboarding@resend.dev     # Optional: sender shown in email flows

# ==========================================
# STORAGE
# ==========================================

# Storage defaults to FILE_STORAGE_BACKEND=convex.
# Run pnpm run storage:setup if you want guided setup for:
#   - convex
#   - s3-primary
#   - s3-mirror

# ==========================================
# SENTRY ERROR MONITORING (Optional)
# ==========================================

# Optional: Sentry DSN for error monitoring and performance tracking
# Get from: https://sentry.io/settings/projects/YOUR_PROJECT/keys/
# VITE_SENTRY_DSN=https://your-project-dsn.ingest.sentry.io/project-id
# Leave commented out to disable Sentry monitoring

# ==========================================
# CONVEX DATABASE (Auto-configured)
# ==========================================

# Convex URLs will be automatically set after running: npx convex dev
# VITE_CONVEX_SITE_URL= set after running: pnpm run setup:convex

# ==========================================
# PLAYWRIGHT E2E AUTH (Optional)
# ==========================================

# Enable only when you want authenticated E2E seeding/login helpers
# ENABLE_E2E_TEST_AUTH=true
# E2E_TEST_SECRET=<shared-secret-for-test-route>
# E2E_USER_EMAIL=e2e-user@local.test
# E2E_USER_PASSWORD=<deterministic-test-password>
# E2E_USER_NAME="E2E User"
# E2E_ADMIN_EMAIL=e2e-admin@local.test
# E2E_ADMIN_PASSWORD=<deterministic-test-password>
# E2E_ADMIN_NAME="E2E Admin"

`;

  writeFileSync(envPath, envContent, 'utf8');

  console.log('✅ Local development environment configured!');
  console.log(`   📁 Created: ${envPath}`);
  console.log('────────────────────────────────────────────────');
  console.log('🔑 Generated Secrets:');
  console.log(`   BETTER_AUTH_SECRET: ${authSecret.substring(0, 10)}...`);
  console.log('────────────────────────────────────────────────\n');
  console.log('🚀 Next steps:');
  console.log('   1. 📋 Review the generated .env.local file');
  console.log('   2. ☁️  Run: npx convex dev --once (initialize Convex project)');
  console.log('   3. ⚙️  Run: pnpm run setup:convex (configure URLs & env vars)');
  console.log('   4. 🔄 Terminal 1: npx convex dev (start Convex backend)');
  console.log('   5. 🎯 Terminal 2: pnpm dev (start frontend development)');
  console.log('');
  console.log("💡 Tip: After step 5, you'll never need to run setup again!");
  console.log(
    '   Future development: run "npx convex dev" in one terminal and "pnpm dev" in another',
  );
  console.log('\n📌 Security Notes:');
  console.log('   • Never commit .env.local to version control');
  console.log('   • Back up these secrets if they guard real data');
  console.log('   • Convex handles encryption at the platform level');
}

main().catch((error) => {
  console.error('\n❌ Failed to set up development environment');
  console.error(error);
  process.exit(1);
});
