#!/usr/bin/env tsx

/**
 * Set up local development environment with secrets and configuration.
 * - BETTER_AUTH_SECRET: 32 bytes for session signing (also needed in Convex Dashboard)
 * - BETTER_AUTH_URL: Base URL for Better Auth (also needed in Convex Dashboard)
 * Run: npm run setup
 */

import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { generateSecret } from '../src/lib/server/crypto.server';

async function main() {
  console.log('🔧 Setting up local development environment...\n');

  const authSecret = await generateSecret(32); // BETTER_AUTH_SECRET: 32 bytes for session signing

  // BETTER_AUTH_URL: Base URL for Better Auth
  const authUrl = 'http://localhost:3000';

  const envPath = join(process.cwd(), '.env.local');

  // Check if .env.local already exists
  if (existsSync(envPath)) {
    console.log('⚠️  .env.local already exists!');
    console.log('   To avoid overwriting existing configuration, here are your generated secrets:');
    console.log('────────────────────────────────────────────────');
    console.log(`BETTER_AUTH_SECRET=${authSecret}`);
    console.log(`BETTER_AUTH_URL=${authUrl}`);
    console.log('────────────────────────────────────────────────\n');
    console.log('📝 Add these to your existing .env.local file.');
    return;
  }

  // Create .env.local with all defaults
  const envContent = `# Local Development Environment
# Generated by: npm run setup
# Generated on: ${new Date().toISOString()}

# ==========================================
# REQUIRED SECRETS (Generated Securely)
# ==========================================

# Signs JWTs for authentication
BETTER_AUTH_SECRET=${authSecret}

# Base URL for Better Auth
BETTER_AUTH_URL=${authUrl}

# ==========================================
# REQUIRED DEFAULTS
# ==========================================

# Set development environment
NODE_ENV=development

# ==========================================
# CONVEX DASHBOARD VARIABLES
# ==========================================
# These variables must also be set in your Convex Dashboard (Project Settings → Environment Variables):
#
# BETTER_AUTH_SECRET=<same-secret-as-above>
# SITE_URL=http://localhost:3000
# RESEND_API_KEY=<your-resend-api-key>          # Optional: for email functionality
# RESEND_EMAIL_SENDER=<your-verified-email>      # Optional: for email functionality
# APP_NAME="TanStack Start Template"             # Optional: for email templates

# ==========================================
# STORAGE (S3-Compatible: MinIO for dev, AWS S3 for prod)
# ==========================================

# Defaults target the local MinIO instance (pnpm dev:storage)
S3_ENDPOINT=http://localhost:9000
S3_REGION=us-west-1
S3_ACCESS_KEY_ID=minioadmin
S3_SECRET_ACCESS_KEY=minioadmin
S3_BUCKET_NAME=application-documents
S3_FORCE_PATH_STYLE=true
S3_PUBLIC_URL=http://localhost:9000

# ==========================================
# CONVEX DATABASE (Auto-configured)
# ==========================================

# Convex URLs will be automatically set after running: npx convex dev
# VITE_CONVEX_URL=your-convex-deployment-url
# VITE_CONVEX_SITE_URL=https://your-app-domain.com

# For production: Convex URLs are automatically configured by Netlify

# ==========================================
# NEXT STEPS
# ==========================================
#
# 1. Copy BETTER_AUTH_SECRET to your Convex Dashboard
# 2. Add SITE_URL=http://localhost:3000 to Convex Dashboard
# 3. Run: npx convex dev (initializes Convex project)
# 4. Add email variables to Convex Dashboard if using email features
`;

  writeFileSync(envPath, envContent, 'utf8');

  console.log('✅ Local development environment configured!');
  console.log(`   📁 Created: ${envPath}`);
  console.log('────────────────────────────────────────────────');
  console.log('🔑 Generated Secrets:');
  console.log(`   BETTER_AUTH_SECRET: ${authSecret.substring(0, 10)}...`);
  console.log(`   BETTER_AUTH_URL: ${authUrl}`);
  console.log('────────────────────────────────────────────────\n');
  console.log('🚀 Ready to develop!');
  console.log('   1. Review the generated .env.local file');
  console.log('   2. Copy BETTER_AUTH_SECRET to Convex Dashboard → Environment Variables');
  console.log('   3. Run: npx convex dev (to initialize Convex project)');
  console.log('   4. Run: pnpm dev');
  console.log('\n📌 Security Notes:');
  console.log('   • Never commit .env.local to version control');
  console.log('   • Back up these secrets if they guard real data');
  console.log('   • Convex handles encryption at the platform level');
}

main().catch((error) => {
  console.error('\n❌ Failed to set up development environment');
  console.error(error);
  process.exit(1);
});
