/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailPendingRouteImport } from './routes/verify-email-pending'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as TestSentryRouteImport } from './routes/test-sentry'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecoverAccountRouteImport } from './routes/recover-account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccountSetupRouteImport } from './routes/account-setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as ApiSentryExampleRouteImport } from './routes/api/sentry-example'
import { Route as ApiReadinessRouteImport } from './routes/api/readiness'
import { Route as ApiParsePdfRouteImport } from './routes/api/parse-pdf'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppOrganizationsIndexRouteImport } from './routes/app/organizations/index'
import { Route as AppChatIndexRouteImport } from './routes/app/chat/index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin/index'
import { Route as AppOrganizationsLayoutRouteImport } from './routes/app/organizations/_layout'
import { Route as AppChatThreadIdRouteImport } from './routes/app/chat/$threadId'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppAdminStatsRouteImport } from './routes/app/admin/stats'
import { Route as AppAdminSecurityRouteImport } from './routes/app/admin/security'
import { Route as AppAdminModelsRouteImport } from './routes/app/admin/models'
import { Route as AppAdminEmailsRouteImport } from './routes/app/admin/emails'
import { Route as AppAdminLayoutRouteImport } from './routes/app/admin/_layout'
import { Route as ApiTestE2eAuthRouteImport } from './routes/api/test/e2e-auth'
import { Route as ApiTestAgentAuthRouteImport } from './routes/api/test/agent-auth'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppOrganizationsSlugIndexRouteImport } from './routes/app/organizations/$slug/index'
import { Route as AppOrganizationsSlugSettingsRouteImport } from './routes/app/organizations/$slug/settings'
import { Route as AppOrganizationsSlugPoliciesRouteImport } from './routes/app/organizations/$slug/policies'
import { Route as AppOrganizationsSlugMembersRouteImport } from './routes/app/organizations/$slug/members'
import { Route as AppOrganizationsSlugIdentityRouteImport } from './routes/app/organizations/$slug/identity'
import { Route as AppOrganizationsSlugDomainsRouteImport } from './routes/app/organizations/$slug/domains'
import { Route as AppOrganizationsSlugAuditRouteImport } from './routes/app/organizations/$slug/audit'

const VerifyEmailPendingRoute = VerifyEmailPendingRouteImport.update({
  id: '/verify-email-pending',
  path: '/verify-email-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSentryRoute = TestSentryRouteImport.update({
  id: '/test-sentry',
  path: '/test-sentry',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverAccountRoute = RecoverAccountRouteImport.update({
  id: '/recover-account',
  path: '/recover-account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSetupRoute = AccountSetupRouteImport.update({
  id: '/account-setup',
  path: '/account-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const ApiSentryExampleRoute = ApiSentryExampleRouteImport.update({
  id: '/api/sentry-example',
  path: '/api/sentry-example',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadinessRoute = ApiReadinessRouteImport.update({
  id: '/api/readiness',
  path: '/api/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParsePdfRoute = ApiParsePdfRouteImport.update({
  id: '/api/parse-pdf',
  path: '/api/parse-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsLayoutRoute = AppOrganizationsLayoutRouteImport.update({
  id: '/organizations/_layout',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppChatThreadIdRoute = AppChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminStatsRoute = AppAdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSecurityRoute = AppAdminSecurityRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminModelsRoute = AppAdminModelsRouteImport.update({
  id: '/admin/models',
  path: '/admin/models',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmailsRoute = AppAdminEmailsRouteImport.update({
  id: '/admin/emails',
  path: '/admin/emails',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLayoutRoute = AppAdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiTestE2eAuthRoute = ApiTestE2eAuthRouteImport.update({
  id: '/api/test/e2e-auth',
  path: '/api/test/e2e-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestAgentAuthRoute = ApiTestAgentAuthRouteImport.update({
  id: '/api/test/agent-auth',
  path: '/api/test/agent-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationsSlugIndexRoute =
  AppOrganizationsSlugIndexRouteImport.update({
    id: '/organizations/$slug/',
    path: '/organizations/$slug/',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsSlugSettingsRoute =
  AppOrganizationsSlugSettingsRouteImport.update({
    id: '/organizations/$slug/settings',
    path: '/organizations/$slug/settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsSlugPoliciesRoute =
  AppOrganizationsSlugPoliciesRouteImport.update({
    id: '/organizations/$slug/policies',
    path: '/organizations/$slug/policies',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsSlugMembersRoute =
  AppOrganizationsSlugMembersRouteImport.update({
    id: '/organizations/$slug/members',
    path: '/organizations/$slug/members',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsSlugIdentityRoute =
  AppOrganizationsSlugIdentityRouteImport.update({
    id: '/organizations/$slug/identity',
    path: '/organizations/$slug/identity',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsSlugDomainsRoute =
  AppOrganizationsSlugDomainsRouteImport.update({
    id: '/organizations/$slug/domains',
    path: '/organizations/$slug/domains',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganizationsSlugAuditRoute =
  AppOrganizationsSlugAuditRouteImport.update({
    id: '/organizations/$slug/audit',
    path: '/organizations/$slug/audit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-setup': typeof AccountSetupRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/recover-account': typeof RecoverAccountRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test-sentry': typeof TestSentryRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email-pending': typeof VerifyEmailPendingRoute
  '/api/health': typeof ApiHealthRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/parse-pdf': typeof ApiParsePdfRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/app/profile': typeof AppProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/agent-auth': typeof ApiTestAgentAuthRoute
  '/api/test/e2e-auth': typeof ApiTestE2eAuthRoute
  '/app/admin': typeof AppAdminLayoutRoute
  '/app/admin/emails': typeof AppAdminEmailsRoute
  '/app/admin/models': typeof AppAdminModelsRoute
  '/app/admin/security': typeof AppAdminSecurityRoute
  '/app/admin/stats': typeof AppAdminStatsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$threadId': typeof AppChatThreadIdRoute
  '/app/organizations': typeof AppOrganizationsLayoutRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/organizations/$slug/audit': typeof AppOrganizationsSlugAuditRoute
  '/app/organizations/$slug/domains': typeof AppOrganizationsSlugDomainsRoute
  '/app/organizations/$slug/identity': typeof AppOrganizationsSlugIdentityRoute
  '/app/organizations/$slug/members': typeof AppOrganizationsSlugMembersRoute
  '/app/organizations/$slug/policies': typeof AppOrganizationsSlugPoliciesRoute
  '/app/organizations/$slug/settings': typeof AppOrganizationsSlugSettingsRoute
  '/app/organizations/$slug/': typeof AppOrganizationsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-setup': typeof AccountSetupRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/recover-account': typeof RecoverAccountRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test-sentry': typeof TestSentryRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email-pending': typeof VerifyEmailPendingRoute
  '/api/health': typeof ApiHealthRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/parse-pdf': typeof ApiParsePdfRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/app/profile': typeof AppProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/agent-auth': typeof ApiTestAgentAuthRoute
  '/api/test/e2e-auth': typeof ApiTestE2eAuthRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/admin/emails': typeof AppAdminEmailsRoute
  '/app/admin/models': typeof AppAdminModelsRoute
  '/app/admin/security': typeof AppAdminSecurityRoute
  '/app/admin/stats': typeof AppAdminStatsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$threadId': typeof AppChatThreadIdRoute
  '/app/organizations': typeof AppOrganizationsIndexRoute
  '/app/chat': typeof AppChatIndexRoute
  '/app/organizations/$slug/audit': typeof AppOrganizationsSlugAuditRoute
  '/app/organizations/$slug/domains': typeof AppOrganizationsSlugDomainsRoute
  '/app/organizations/$slug/identity': typeof AppOrganizationsSlugIdentityRoute
  '/app/organizations/$slug/members': typeof AppOrganizationsSlugMembersRoute
  '/app/organizations/$slug/policies': typeof AppOrganizationsSlugPoliciesRoute
  '/app/organizations/$slug/settings': typeof AppOrganizationsSlugSettingsRoute
  '/app/organizations/$slug': typeof AppOrganizationsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-setup': typeof AccountSetupRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/recover-account': typeof RecoverAccountRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/test-sentry': typeof TestSentryRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email-pending': typeof VerifyEmailPendingRoute
  '/api/health': typeof ApiHealthRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/parse-pdf': typeof ApiParsePdfRoute
  '/api/readiness': typeof ApiReadinessRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/app/profile': typeof AppProfileRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/test/agent-auth': typeof ApiTestAgentAuthRoute
  '/api/test/e2e-auth': typeof ApiTestE2eAuthRoute
  '/app/admin/_layout': typeof AppAdminLayoutRoute
  '/app/admin/emails': typeof AppAdminEmailsRoute
  '/app/admin/models': typeof AppAdminModelsRoute
  '/app/admin/security': typeof AppAdminSecurityRoute
  '/app/admin/stats': typeof AppAdminStatsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chat/$threadId': typeof AppChatThreadIdRoute
  '/app/organizations/_layout': typeof AppOrganizationsLayoutRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/organizations/$slug/audit': typeof AppOrganizationsSlugAuditRoute
  '/app/organizations/$slug/domains': typeof AppOrganizationsSlugDomainsRoute
  '/app/organizations/$slug/identity': typeof AppOrganizationsSlugIdentityRoute
  '/app/organizations/$slug/members': typeof AppOrganizationsSlugMembersRoute
  '/app/organizations/$slug/policies': typeof AppOrganizationsSlugPoliciesRoute
  '/app/organizations/$slug/settings': typeof AppOrganizationsSlugSettingsRoute
  '/app/organizations/$slug/': typeof AppOrganizationsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-setup'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/recover-account'
    | '/register'
    | '/reset-password'
    | '/test-sentry'
    | '/two-factor'
    | '/verify-email-pending'
    | '/api/health'
    | '/api/metrics'
    | '/api/parse-pdf'
    | '/api/readiness'
    | '/api/sentry-example'
    | '/app/profile'
    | '/invite/$token'
    | '/app/'
    | '/api/auth/$'
    | '/api/test/agent-auth'
    | '/api/test/e2e-auth'
    | '/app/admin'
    | '/app/admin/emails'
    | '/app/admin/models'
    | '/app/admin/security'
    | '/app/admin/stats'
    | '/app/admin/users'
    | '/app/chat/$threadId'
    | '/app/organizations'
    | '/app/admin/'
    | '/app/chat/'
    | '/app/organizations/'
    | '/app/organizations/$slug/audit'
    | '/app/organizations/$slug/domains'
    | '/app/organizations/$slug/identity'
    | '/app/organizations/$slug/members'
    | '/app/organizations/$slug/policies'
    | '/app/organizations/$slug/settings'
    | '/app/organizations/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-setup'
    | '/forgot-password'
    | '/login'
    | '/recover-account'
    | '/register'
    | '/reset-password'
    | '/test-sentry'
    | '/two-factor'
    | '/verify-email-pending'
    | '/api/health'
    | '/api/metrics'
    | '/api/parse-pdf'
    | '/api/readiness'
    | '/api/sentry-example'
    | '/app/profile'
    | '/invite/$token'
    | '/app'
    | '/api/auth/$'
    | '/api/test/agent-auth'
    | '/api/test/e2e-auth'
    | '/app/admin'
    | '/app/admin/emails'
    | '/app/admin/models'
    | '/app/admin/security'
    | '/app/admin/stats'
    | '/app/admin/users'
    | '/app/chat/$threadId'
    | '/app/organizations'
    | '/app/chat'
    | '/app/organizations/$slug/audit'
    | '/app/organizations/$slug/domains'
    | '/app/organizations/$slug/identity'
    | '/app/organizations/$slug/members'
    | '/app/organizations/$slug/policies'
    | '/app/organizations/$slug/settings'
    | '/app/organizations/$slug'
  id:
    | '__root__'
    | '/'
    | '/account-setup'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/recover-account'
    | '/register'
    | '/reset-password'
    | '/test-sentry'
    | '/two-factor'
    | '/verify-email-pending'
    | '/api/health'
    | '/api/metrics'
    | '/api/parse-pdf'
    | '/api/readiness'
    | '/api/sentry-example'
    | '/app/profile'
    | '/invite/$token'
    | '/app/'
    | '/api/auth/$'
    | '/api/test/agent-auth'
    | '/api/test/e2e-auth'
    | '/app/admin/_layout'
    | '/app/admin/emails'
    | '/app/admin/models'
    | '/app/admin/security'
    | '/app/admin/stats'
    | '/app/admin/users'
    | '/app/chat/$threadId'
    | '/app/organizations/_layout'
    | '/app/admin/'
    | '/app/chat/'
    | '/app/organizations/'
    | '/app/organizations/$slug/audit'
    | '/app/organizations/$slug/domains'
    | '/app/organizations/$slug/identity'
    | '/app/organizations/$slug/members'
    | '/app/organizations/$slug/policies'
    | '/app/organizations/$slug/settings'
    | '/app/organizations/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSetupRoute: typeof AccountSetupRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RecoverAccountRoute: typeof RecoverAccountRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TestSentryRoute: typeof TestSentryRoute
  TwoFactorRoute: typeof TwoFactorRoute
  VerifyEmailPendingRoute: typeof VerifyEmailPendingRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  ApiParsePdfRoute: typeof ApiParsePdfRoute
  ApiReadinessRoute: typeof ApiReadinessRoute
  ApiSentryExampleRoute: typeof ApiSentryExampleRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTestAgentAuthRoute: typeof ApiTestAgentAuthRoute
  ApiTestE2eAuthRoute: typeof ApiTestE2eAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email-pending': {
      id: '/verify-email-pending'
      path: '/verify-email-pending'
      fullPath: '/verify-email-pending'
      preLoaderRoute: typeof VerifyEmailPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-sentry': {
      id: '/test-sentry'
      path: '/test-sentry'
      fullPath: '/test-sentry'
      preLoaderRoute: typeof TestSentryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-account': {
      id: '/recover-account'
      path: '/recover-account'
      fullPath: '/recover-account'
      preLoaderRoute: typeof RecoverAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-setup': {
      id: '/account-setup'
      path: '/account-setup'
      fullPath: '/account-setup'
      preLoaderRoute: typeof AccountSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/sentry-example': {
      id: '/api/sentry-example'
      path: '/api/sentry-example'
      fullPath: '/api/sentry-example'
      preLoaderRoute: typeof ApiSentryExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/readiness': {
      id: '/api/readiness'
      path: '/api/readiness'
      fullPath: '/api/readiness'
      preLoaderRoute: typeof ApiReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-pdf': {
      id: '/api/parse-pdf'
      path: '/api/parse-pdf'
      fullPath: '/api/parse-pdf'
      preLoaderRoute: typeof ApiParsePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/organizations/': {
      id: '/app/organizations/'
      path: '/organizations'
      fullPath: '/app/organizations/'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/chat'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/_layout': {
      id: '/app/organizations/_layout'
      path: '/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AppOrganizationsLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$threadId': {
      id: '/app/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/app/chat/$threadId'
      preLoaderRoute: typeof AppChatThreadIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/stats': {
      id: '/app/admin/stats'
      path: '/admin/stats'
      fullPath: '/app/admin/stats'
      preLoaderRoute: typeof AppAdminStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/security': {
      id: '/app/admin/security'
      path: '/admin/security'
      fullPath: '/app/admin/security'
      preLoaderRoute: typeof AppAdminSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/models': {
      id: '/app/admin/models'
      path: '/admin/models'
      fullPath: '/app/admin/models'
      preLoaderRoute: typeof AppAdminModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/emails': {
      id: '/app/admin/emails'
      path: '/admin/emails'
      fullPath: '/app/admin/emails'
      preLoaderRoute: typeof AppAdminEmailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/_layout': {
      id: '/app/admin/_layout'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/test/e2e-auth': {
      id: '/api/test/e2e-auth'
      path: '/api/test/e2e-auth'
      fullPath: '/api/test/e2e-auth'
      preLoaderRoute: typeof ApiTestE2eAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test/agent-auth': {
      id: '/api/test/agent-auth'
      path: '/api/test/agent-auth'
      fullPath: '/api/test/agent-auth'
      preLoaderRoute: typeof ApiTestAgentAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/organizations/$slug/': {
      id: '/app/organizations/$slug/'
      path: '/organizations/$slug'
      fullPath: '/app/organizations/$slug/'
      preLoaderRoute: typeof AppOrganizationsSlugIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$slug/settings': {
      id: '/app/organizations/$slug/settings'
      path: '/organizations/$slug/settings'
      fullPath: '/app/organizations/$slug/settings'
      preLoaderRoute: typeof AppOrganizationsSlugSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$slug/policies': {
      id: '/app/organizations/$slug/policies'
      path: '/organizations/$slug/policies'
      fullPath: '/app/organizations/$slug/policies'
      preLoaderRoute: typeof AppOrganizationsSlugPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$slug/members': {
      id: '/app/organizations/$slug/members'
      path: '/organizations/$slug/members'
      fullPath: '/app/organizations/$slug/members'
      preLoaderRoute: typeof AppOrganizationsSlugMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$slug/identity': {
      id: '/app/organizations/$slug/identity'
      path: '/organizations/$slug/identity'
      fullPath: '/app/organizations/$slug/identity'
      preLoaderRoute: typeof AppOrganizationsSlugIdentityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$slug/domains': {
      id: '/app/organizations/$slug/domains'
      path: '/organizations/$slug/domains'
      fullPath: '/app/organizations/$slug/domains'
      preLoaderRoute: typeof AppOrganizationsSlugDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$slug/audit': {
      id: '/app/organizations/$slug/audit'
      path: '/organizations/$slug/audit'
      fullPath: '/app/organizations/$slug/audit'
      preLoaderRoute: typeof AppOrganizationsSlugAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminLayoutRoute: typeof AppAdminLayoutRoute
  AppAdminEmailsRoute: typeof AppAdminEmailsRoute
  AppAdminModelsRoute: typeof AppAdminModelsRoute
  AppAdminSecurityRoute: typeof AppAdminSecurityRoute
  AppAdminStatsRoute: typeof AppAdminStatsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppChatThreadIdRoute: typeof AppChatThreadIdRoute
  AppOrganizationsLayoutRoute: typeof AppOrganizationsLayoutRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
  AppOrganizationsSlugAuditRoute: typeof AppOrganizationsSlugAuditRoute
  AppOrganizationsSlugDomainsRoute: typeof AppOrganizationsSlugDomainsRoute
  AppOrganizationsSlugIdentityRoute: typeof AppOrganizationsSlugIdentityRoute
  AppOrganizationsSlugMembersRoute: typeof AppOrganizationsSlugMembersRoute
  AppOrganizationsSlugPoliciesRoute: typeof AppOrganizationsSlugPoliciesRoute
  AppOrganizationsSlugSettingsRoute: typeof AppOrganizationsSlugSettingsRoute
  AppOrganizationsSlugIndexRoute: typeof AppOrganizationsSlugIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminLayoutRoute: AppAdminLayoutRoute,
  AppAdminEmailsRoute: AppAdminEmailsRoute,
  AppAdminModelsRoute: AppAdminModelsRoute,
  AppAdminSecurityRoute: AppAdminSecurityRoute,
  AppAdminStatsRoute: AppAdminStatsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppChatThreadIdRoute: AppChatThreadIdRoute,
  AppOrganizationsLayoutRoute: AppOrganizationsLayoutRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
  AppOrganizationsSlugAuditRoute: AppOrganizationsSlugAuditRoute,
  AppOrganizationsSlugDomainsRoute: AppOrganizationsSlugDomainsRoute,
  AppOrganizationsSlugIdentityRoute: AppOrganizationsSlugIdentityRoute,
  AppOrganizationsSlugMembersRoute: AppOrganizationsSlugMembersRoute,
  AppOrganizationsSlugPoliciesRoute: AppOrganizationsSlugPoliciesRoute,
  AppOrganizationsSlugSettingsRoute: AppOrganizationsSlugSettingsRoute,
  AppOrganizationsSlugIndexRoute: AppOrganizationsSlugIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSetupRoute: AccountSetupRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RecoverAccountRoute: RecoverAccountRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TestSentryRoute: TestSentryRoute,
  TwoFactorRoute: TwoFactorRoute,
  VerifyEmailPendingRoute: VerifyEmailPendingRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  ApiParsePdfRoute: ApiParsePdfRoute,
  ApiReadinessRoute: ApiReadinessRoute,
  ApiSentryExampleRoute: ApiSentryExampleRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTestAgentAuthRoute: ApiTestAgentAuthRoute,
  ApiTestE2eAuthRoute: ApiTestE2eAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
